version: v1.0
name: Deploy to Production
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Build - Production
    dependencies: []
    task:
      env_vars:
        - name: API_BASE_URL
          value: 'https://prod-duplica-api.herokuapp.com'
      jobs:
        - name: Build
          commands:
            - checkout --use-cache
            - cache restore
            - npm run build
            - cache delete website-build
            - cache store website-build dist
  - name: Deploy - Production
    task:
      secrets:
        - name: DuplicaWeb
      jobs:
        - name: Deploy to Production in S3
          commands:
            - checkout
            - aws s3 rm s3://$BUCKET_NAME_PRD --recursive
            - cache restore website-build
            - aws s3 sync dist s3://$BUCKET_NAME_PRD --acl public-read
      dependencies:
        - Build - Production
