version: v1.0
name: Deploy to Production
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Deploy
    task:
      secrets:
        - name: DuplicaSecrets
      jobs:
        - name: Deploy to Production in S3
          commands:
            - checkout
            - cache restore website-build
            - aws s3 sync "dist" "s3://$BUCKET_NAME_PRD" --acl "public-read"
